# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Testing CI for esbuild-plugin-sass

defaults:
  run:
    shell: bash

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:

    strategy:
      matrix:
        node-version: [10.x, 14.x, 16.x]
        runs-on: [windows-2019, ubuntu-20.04]

    runs-on: ${{ matrix.runs-on }}

    steps:
    - uses: actions/checkout@v2
    - uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.25.0
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: pnpm ci
    - run: pnpm run build --if-present
    - run: pnpm test
      shell: bash

  all-checks-passed:
    runs-on: ubuntu-20.04
    needs: test
    steps:
    - uses: actions/checkout@v2
